### ISSUE TITLE
6.3.0 Changes 

### ISSUE THREAD

**Issue by joshuaNathaniel** [yorlov/hello-bitbucket-addon#1]
**hello-bitbucket-addon/src/main/resources/js/hello.js**
`Uncaught Error: AMD module hcb/twentytwenty must not depend on internal module(s) bitbucket/internal/layout/pull-request. See the API changelog for details: https://developer.atlassian.com/server/bitbucket/reference/api-changelog/#expected-future-changes
`
@yorlov Hi, I was just wondering since Atlassian is restricting access to bitbucket/internal what the next viable alternative would be here and I'm asking you because maybe you have your finger on the pulse. I looked through the [public api](https://docs.atlassian.com/bitbucket-server/docs/6.3.0/reference/javascript/) but nothing jumped out at me.

**Comment by yorlov** [comment]
@joshuaNathaniel at your own risk you can [create an amd-wrapper with name starts with _bitbucket-plugin-_](https://github.com/yorlov/hello-bitbucket-addon/blob/master/src/main/resources/js/pull-request-layout.js) and use it instead of internal module
